### ISSUE TITLE
Packed is invalid after restart

### ISSUE THREAD

**Issue by tingfeng-key** [Lonami/grammers#135] opened 2022-08-26 02:27 UTC
The code for getting packed is as follows:
```rust
while let Some(update) = self.client.next_update().await? {
      if let Update::NewMessage(message) = update {
          if let Some(Chat::User(types::User(user))) = message.sender() {
              warn!(
                  "{}",
                  serde_json::to_string(
                      &Chat::from_user(user.into()).pack().to_bytes()
                  )
                  .unwrap()
              );
          }
    }
```
After printing the packed string, stop the program and execute the following code:
```rust
let encode: Vec<u8> = vec![];//Real packed.to_ Bytes data

let decode = PackedChat::from_bytes(&encode).expect("error");

let input_user = decode.try_to_input_user().expect("input error");

//get_full_user is the method that implements tl::functions::users::GetFullUser
let full_user = self.client.clone().get_full_user(input_user.clone()).await;

warn!("{:#?}", full_user);

//get_users is the method that implements tl::functions::users::GetUsers
let users = self.client.clone().get_users(vec![input_user]).await;
warn!("{:#?}", users);

let msg = InputMessage::text("hi");
let m = self.client.send_message(decode, msg).await;
warn!("{:#?}", m);
```
After running the program, it prints as follows：
```rust
Err(
    Other(
        Rpc(
            RpcError {
                code: 400,
                name: "USER_ID_INVALID",
                value: None,
                caused_by: Some(
                    3054459160,
                ),
            },
        ),
    ),
)
Ok(
    [],
)
Err(
    Rpc(
        RpcError {
            code: 400,
            name: "PEER_ID_INVALID",
            value: None,
            caused_by: Some(
                228423076,
            ),
        },
    ),
)
```
The implementation of get_users and get_full_user is as follows：
```rust
    pub async fn get_full_user(
        &mut self,
        id: tl::enums::InputUser,
    ) -> Result<(tl::types::UserFull, tl::types::User), UserError> {
        match self.invoke(&tl::functions::users::GetFullUser { id }).await {
            Ok(tl::enums::users::UserFull::Full(user_full)) => {
                let full_user = match user_full.full_user {
                    tl::enums::UserFull::Full(user) => user,
                };

                let user_base = match user_full.users.first() {
                    Some(tl::enums::User::Empty(_)) => Err(UserError::EmptyUser),
                    Some(tl::enums::User::User(user)) => Ok(user.clone()),
                    None => Err(UserError::EmptyUser),
                }?;
                Ok((full_user, user_base))
            }
            Err(e) => Err(UserError::Other(e)),
        }
    }

    pub async fn get_users(
        &mut self,
        id: Vec<tl::enums::InputUser>,
    ) -> Result<Vec<crate::types::chat::Chat>, InvocationError> {
        let users = self.invoke(&tl::functions::users::GetUsers { id }).await?;
        let mut chats = vec![];
        for user in users {
            chats.push(crate::types::chat::Chat::from_user(user))
        }
        Ok(chats)
    }
```

**Comment by tingfeng-key** [comment] 2022-08-26 02:34
I checked some information：
#https://github.com/tdlib/td/issues/2035

**Comment by Lonami** [comment] 2022-08-26 16:45
I have added the following code to the [`dialogs.rs` example](https://github.com/Lonami/grammers/blob/e5252e02f57cc90820c75f27fc23bac6c7d9971b/lib/grammers-client/examples/dialogs.rs) (inside the loop which prints the chats):

```rust
let repacked = PackedChat::from_bytes(&dialog.chat().pack().to_bytes()).unwrap();
assert_eq!(repacked, dialog.chat().pack());
if let Some(input_user) = repacked.try_to_input_user() {
    let full_user = get_full_user(&mut client_handle, input_user).await;
    println!("{:#?}", full_user);
}
```

The assert succeeds. None of the `get_full_user` calls (your function) failed in the way you posted (only flood wait errors). To me this indicates that you likely packed the chat in account A, and are attempting to unpack and use it in account B. This won't work. Is that the case?

**Comment by Lonami** [comment] 2022-08-26 16:46
Also, if I debug the values of `repacked`, they are the same, even if I restart the program.

**Comment by tingfeng-key** [comment] 2022-08-27 04:06
is executed within the same session file for one account only.

My process is to save the bytes value of the sender's Packed in Update, copy it out from the running terminal, put it in a new method, recompile and execute, it will prompt like that

The user of dialogs is my contact, but the user of the group in Update is not my contact, is it not my contact that is not available?

**Comment by Lonami** [comment] 2022-08-28 09:54
Are you fetching the sender from a private conversation, a small group chat, or a megagroup? If it's a megagroup, how many members does it have? If possible, what do the packed bytes look like (are there a lot of 0's)?

**Comment by Lonami** [comment] 2022-08-28 10:13
If I try to print a sender from a private conversation, the hash looks normal. I can print it, embed it, restart the application, and `get_full_user` works. I then tried to do this in a freshly-created new small group chat, and a freshly-created megagroup (migrated from a freshly-created small group chat). In all the cases the printed packed bytes are the same so they all work. Unfortunately this means I cannot reproduce the issue.

**Comment by tingfeng-key** [comment] 2022-08-28 14:20
From the printed results (`PackedChat { ty: Megagroup,`), they are basically `Megagroups`. I put a few `user.packed.to_bytes` data out:
```
[2,18,63,154,114,88,1,0,0,0,113,173,169,225,10,236,192,232]
[2,18,143,16,38,88,1,0,0,0,34,124,209,138,25,147,20,1]
[2,18,117,46,92,31,0,0,0,0,232,62,60,4,212,194,36,90]
[2,18,4,252,4,66,1,0,0,0,128,51,170,251,194,246,66,120]
[2,18,216,17,114,67,1,0,0,0,47,66,118,150,250,85,209,28]
```

In terms of number of people, some groups have more than 1,000, more than 2,000, and there are tens of thousands of people, such as 110,000 and 50,000.

**Comment by tingfeng-key** [comment] 2022-08-28 14:27
I tried it with `Pyrogram` this weekend, and I found that some sender IDs and access_hash are not saved to `sqlite` (and some are). So I guess, is it possible that the user who sent the message does not exist in `updates.users`?

**Comment by tingfeng-key** [comment] 2022-08-28 14:38
I have a major discovery, the self.msg.peer_id in the `message.sender `method is of type `PeerChannel`
```rust
pub fn sender(&self) -> Option<types::Chat> {
        self.msg
            .from_id
            .as_ref()
            .or({
                println!(
                    "hi,{},{}, {:#?}",
                    !self.msg.out,
                    matches!(self.msg.peer_id, tl::enums::Peer::User(_)),
                    self.msg.peer_id
                );
                // Incoming messages in private conversations don't include `from_id` since
                // layer 119, but the sender can only be the chat we're in.
                if !self.msg.out && matches!(self.msg.peer_id, tl::enums::Peer::User(_)) {
                    println!("ok");
                    Some(&self.msg.peer_id)
                } else {
                    println!("None");
                    None
                }
            })
            .map(|from| utils::always_find_entity(from, &self.chats, &self.client))
    }
```
One of the data print results is as follows：
```rust
hi,true,false, Channel(
    PeerChannel {
        channel_id: 1336931257,
    },
)
None
```

**Comment by Lonami** [comment] 2022-08-28 20:50
The packed values you posted seem fine (access hash is non-zero). I really don't know why Telegram refuses to use those values. Does it work if you use `get_full_user` immediately when the update arrives (rather than printing and then restarting the program)?

My only guess would be that you were printing the `min` `access_hash`, but I don't think that's it, because `min` users are ignored (line 63). But maybe it is using the `min` hash and I haven't dug enough:

https://github.com/Lonami/grammers/blob/e5252e02f57cc90820c75f27fc23bac6c7d9971b/lib/grammers-session/src/chat/hash_cache.rs#L59-L74

**Comment by Lonami** [comment] 2022-08-28 20:56
Yeah perhaps it's picking up the `min` user, it's the only sensible explanation.

**Comment by Lonami** [comment] 2022-08-28 21:39
Using the `git` version with the above commit, does it work for you now?

**Comment by tingfeng-key** [comment] 2022-08-29 01:01
I updated it and removed the print first, but the result is the same

**Comment by tingfeng-key** [comment] 2022-08-29 02:09
I submitted a minimal code sample:
[code](https://github.com/tingfeng-key/grammers_app_test.git)

operation result：
![image](https://user-images.githubusercontent.com/13976521/187109157-a3d2593b-b55d-47e9-a3ff-734239817356.png)

**Comment by Lonami** [comment] 2022-08-29 11:37
Can you try again with the above commit?

**Comment by tingfeng-key** [comment] 2022-08-29 14:02
Using the newly submitted data can be printed twice, and then the operation will be terminated. The exception is as follows:
```rust
thread 'main' panicked at 'gap is detected while applying difference: Gap', /Users/xxx/.cargo/git/checkouts/grammers-689e30b82f69dcd5/3c401b3/lib/grammers-session/src/message_box/mod.rs:678:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1035:23
   4: grammers_session::message_box::<impl grammers_session::message_box::defs::MessageBox>::apply_difference_type
             at /Users/wzl/.cargo/git/checkouts/grammers-689e30b82f69dcd5/3c401b3/lib/grammers-session/src/message_box/mod.rs:677:9
   5: grammers_session::message_box::<impl grammers_session::message_box::defs::MessageBox>::apply_difference
             at /Users/wzl/.cargo/git/checkouts/grammers-689e30b82f69dcd5/3c401b3/lib/grammers-session/src/message_box/mod.rs:586:17
   6: grammers_client::client::updates::<impl grammers_client::client::client::Client>::next_update::{{closure}}
             at /Users/wzl/.cargo/git/checkouts/grammers-689e30b82f69dcd5/3c401b3/lib/grammers-client/src/client/updates.rs:62:21
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   8: grammers_app_test::async_main::{{closure}}
             at ./src/main.rs:99:57
```

**Comment by Lonami** [comment] 2022-08-29 17:24
Well, at least this likely confirms that the problem is indeed Telegram sending a `min` `access_hash` (because your packed bytes do contain a non-zero hash), but for some reason, even when applying the result from `getDifference`, the hash is still missing and it's treated again as a gap… I'll need to find a way to reproduce this issue.

**Comment by tingfeng-key** [comment] 2022-08-30 00:47
OK, I hope it can be handled as soon as possible. Thank you for your efforts

**Comment by Lonami** [comment] 2022-08-31 14:35
The panic you experienced should no longer occur. Could you try again? From my tests, sometimes `getDifference` also returns `min` users (which leads to `PackedChat` not being valid). I don't know if this will be the case for you too or if it was an outlier.

**Comment by Lonami** [comment] 2022-08-31 15:27
If possible, please test **without** https://github.com/Lonami/grammers/commit/a21d385af7a288212822012a215d75832bac124e. Ideally test with commit https://github.com/Lonami/grammers/commit/b1cfcd1efc96913d525ecd489001106d84084cde. (The very latest commit may make it more difficult to confirm that the fix works).

**Comment by tingfeng-key** [comment] 2022-08-31 16:10
> sometimes getDifference also returns min users (which leads to PackedChat not being valid)
Thank you, my test results are exactly as you said.

**Comment by tingfeng-key** [comment] 2022-08-31 16:15
I can use User.min to filter users who cannot min. But the structure tuple in the client's Chat::User is a tl::types::user alias of pub(crate), can we add the is_min method to achieve this effect? Or is there any other better way?

**Comment by Lonami** [comment] 2022-08-31 19:30
What error do you get when using the library at that commit? Does it work? Does it panic? Or does it fail with an error?

**Comment by tingfeng-key** [comment] 2022-09-01 01:35
With the committed version, it works fine and doesn't panic anymore. But when running get_full_user, USER_ID_INVALID will appear intermittently, which is not as frequent as before (almost all errors before). After I use user.0.min == false to filter before get_full_user. All operations will be successful.

**Comment by tingfeng-key** [comment] 2022-09-04 17:17
When I run get_full_user for a while, the error starts to appear, and the error is persistent:
```rust
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: rpc error 400: USER_ID_INVALID caused by users.getFullUser    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: rpc error 400: USER_ID_INVALID caused by users.getFullUser    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: Connection reset by peer (os error 54)    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: Broken pipe (os error 32)     
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes      
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: Broken pipe (os error 32)     
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes       
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: read 0 bytes    
<unknown time> ERROR cli::telegram: full_user_error,channel error: request error: read error, IO failed: Broken pipe (os error 32)  
```

**Comment by Lonami** [comment] 2024-06-23 18:24
It's been a while so I'll close this issue, as there's been some work trying to get reconnection to be more reliable. As for the packed chats becoming invalid, I would need more concrete evidence I could test myself.

**Closed by Lonami** 2024-06-23 18:24 UTC
